//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAssessment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetAssessment.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string ACCESSORIES {
            get {
                return ResourceManager.GetString("ACCESSORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotNetAssessment.
        /// </summary>
        public static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average customer score.
        /// </summary>
        public static string AVERAGE_CUSTOMER_SCORE {
            get {
                return ResourceManager.GetString("AVERAGE_CUSTOMER_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CATEGORIES {
            get {
                return ResourceManager.GetString("CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2019 Simpson Industries Ltd.
        /// </summary>
        public static string COPYRIGHT_NOTICE {
            get {
                return ResourceManager.GetString("COPYRIGHT_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pizza ovens.
        /// </summary>
        public static string DEFAULT_SEARCH {
            get {
                return ResourceManager.GetString("DEFAULT_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DETAILS {
            get {
                return ResourceManager.GetString("DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NEXT {
            get {
                return ResourceManager.GetString("NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accessories found..
        /// </summary>
        public static string NO_ACCESSORIES_FOUND {
            get {
                return ResourceManager.GetString("NO_ACCESSORIES_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No related products found..
        /// </summary>
        public static string NO_RELATED_PRODUCTS_FOUND {
            get {
                return ResourceManager.GetString("NO_RELATED_PRODUCTS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PREVIOUS {
            get {
                return ResourceManager.GetString("PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related products.
        /// </summary>
        public static string RELATED_PRODUCTS {
            get {
                return ResourceManager.GetString("RELATED_PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review count.
        /// </summary>
        public static string REVIEW_COUNT {
            get {
                return ResourceManager.GetString("REVIEW_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result.
        /// </summary>
        public static string SEARCH_RESULT {
            get {
                return ResourceManager.GetString("SEARCH_RESULT", resourceCulture);
            }
        }
    }
}
