export interface ProductResponse {
    from: number;
    to: number;
    currentPage: number;
    total: number;
    totalPages: number;
    queryTime: string;
    totalTime: string;
    partial: boolean;
    canonicalUrl: string;
    products?: (Product)[] | null;
  }
  export interface Product {
    sku: number;
    score?: null;
    productId?: number | null;
    name: string;
    source?: string | null;
    type: string;
    startDate: string;
    new: boolean;
    active: boolean;
    lowPriceGuarantee: boolean;
    activeUpdateDate: string;
    regularPrice: number;
    salePrice: number;
    clearance: boolean;
    onSale: boolean;
    planPrice?: null;
    priceWithPlan?: (null)[] | null;
    contracts?: (null)[] | null;
    priceRestriction?: null;
    priceUpdateDate: string;
    digital: boolean;
    preowned: boolean;
    carriers?: (null)[] | null;
    planFeatures?: (null)[] | null;
    devices?: (null)[] | null;
    carrierPlans?: (null)[] | null;
    technologyCode?: null;
    carrierModelNumber?: null;
    earlyTerminationFees?: (null)[] | null;
    monthlyRecurringCharge: string;
    monthlyRecurringChargeGrandTotal: string;
    activationCharge: string;
    minutePrice: string;
    planCategory?: null;
    planType?: null;
    familyIndividualCode?: null;
    validFrom?: null;
    validUntil?: null;
    carrierPlan?: null;
    outletCenter?: null;
    secondaryMarket?: null;
    frequentlyPurchasedWith?: (FrequentlyPurchasedWith | null)[] | null;
    accessories?: (null)[] | null;
    relatedProducts?: (null)[] | null;
    requiredParts?: (null)[] | null;
    techSupportPlans?: (null)[] | null;
    crossSell?: (null)[] | null;
    salesRankShortTerm?: number | null;
    salesRankMediumTerm?: number | null;
    salesRankLongTerm?: number | null;
    bestSellingRank?: number | null;
    url: string;
    spin360Url?: null;
    mobileUrl: string;
    affiliateUrl?: null;
    addToCartUrl: string;
    affiliateAddToCartUrl?: null;
    linkShareAffiliateUrl: string;
    linkShareAffiliateAddToCartUrl: string;
    upc: string;
    productTemplate: string;
    categoryPath?: (CategoryPath)[] | null;
    alternateCategories?: (null)[] | null;
    lists?: (null)[] | null;
    customerReviewCount?: number | null;
    customerReviewAverage?: number | null;
    customerTopRated: boolean;
    format?: string | null;
    freeShipping?: boolean | null;
    freeShippingEligible: boolean;
    inStoreAvailability: boolean;
    inStoreAvailabilityText: string;
    inStoreAvailabilityUpdateDate: string;
    itemUpdateDate: string;
    onlineAvailability: boolean;
    onlineAvailabilityText: string;
    onlineAvailabilityUpdateDate: string;
    releaseDate?: string | null;
    shippingCost: number | string;
    shipping?: (Shipping | null)[] | null;
    shippingLevelsOfService?: (ShippingLevelsOfService | null)[] | null;
    specialOrder: boolean;
    shortDescription?: string | null;
    class: string;
    classId: number;
    subclass: string;
    subclassId: number;
    department: string;
    departmentId: number;
    protectionPlanTerm: string;
    protectionPlanType?: null;
    protectionPlanLowPrice: string;
    protectionPlanHighPrice: string;
    buybackPlans?: (null)[] | null;
    protectionPlans?: (null)[] | null;
    protectionPlanDetails?: (null)[] | null;
    productFamilies?: (null)[] | null;
    productVariations?: (null)[] | null;
    aspectRatio?: null;
    screenFormat?: string | null;
    lengthInMinutes?: number | null;
    mpaaRating?: string | null;
    plot?: string | null;
    studio?: string | null;
    theatricalReleaseDate?: string | null;
    description?: null;
    manufacturer?: string | null;
    modelNumber: string;
    images?: (Images)[] | null;
    image: string;
    largeFrontImage: string;
    mediumImage: string;
    thumbnailImage: string;
    largeImage: string;
    alternateViewsImage?: null;
    angleImage?: null;
    backViewImage?: null;
    energyGuideImage?: null;
    leftViewImage?: null;
    accessoriesImage?: null;
    remoteControlImage?: null;
    rightViewImage?: null;
    topViewImage?: null;
    albumTitle: string;
    artistName?: null;
    artistId?: null;
    originalReleaseDate?: null;
    parentalAdvisory?: null;
    mediaCount?: null;
    monoStereo?: null;
    studioLive?: null;
    condition: string;
    inStorePickup: boolean;
    friendsAndFamilyPickup: boolean;
    homeDelivery: boolean;
    quantityLimit?: number | null;
    fulfilledBy?: string | null;
    members?: (null)[] | null;
    bundledIn?: (null)[] | null;
    albumLabel?: null;
    genre?: string | null;
    color?: null;
    depth?: null;
    dollarSavings: number;
    percentSavings: string;
    tradeInValue: string;
    height?: null;
    orderable: string;
    weight?: null;
    shippingWeight: number;
    width?: null;
    warrantyLabor?: null;
    warrantyParts?: null;
    softwareAge?: null;
    softwareGrade?: null;
    platform?: null;
    numberOfPlayers?: null;
    softwareNumberOfPlayers?: null;
    esrbRating?: null;
    longDescription?: string | null;
    includedItemList?: (null)[] | null;
    marketplace?: boolean | null;
    listingId?: null;
    sellerId?: null;
    shippingRestrictions?: null;
    proposition65WarningMessage?: null;
    proposition65WarningType: string;
    productAspectRatio?: string | null;
  }
  export interface FrequentlyPurchasedWith {
    sku: number;
  }
  export interface CategoryPath {
    id: string;
    name: string;
  }
  export interface Shipping {
    ground: number;
    secondDay: number | string;
    nextDay: number | string;
    vendorDelivery: string;
  }
  export interface ShippingLevelsOfService {
    serviceLevelId: number;
    serviceLevelName: string;
    unitShippingPrice: number;
  }
  export interface Images {
    rel: string;
    unitOfMeasure: string;
    width: string;
    height: string;
    href: string;
  }
  